### ISSUE TITLE
unexpected token (NEWLINE)

### ISSUE THREAD

**Issue by steev** [alunduil/etest#54] opened 2015-01-15 00:23 UTC
$ etest -d -v
Error: /home/steev/sandbox/gentoo-x86/app-admin/sudo/sudo-1.8.11_p2.ebuild
13: uri_prefix=
               ^
unexpected token (NEWLINE):

**Comment by alunduil** [comment] 2015-01-25 17:15
duplicate of #26.

**Closed by alunduil** 2015-01-25 17:15 UTC
Labels: duplicate
